# SPDX-License-Identifier: MIT-0
---
- name: Install apache and required utilities
  ansible.builtin.package:
    name:
      - apache2
      - apache2-utils
      - gettext-base  # Provides envsubst for environment variable substitution
    state: present
    update_cache: true

- name: Start apache2 service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: not ansible_check_mode # Don't start service in check_mode if not installed yet
