---
# Import the apache-setup-playbook playbook for testing
- name: Import apache-setup-playbook playbook
  ansible.builtin.import_playbook: ../../../playbooks/apache_setup.yml
  vars:
    target: webservers
