name: CI - Apache Setup Playbook

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'playbooks/apache-setup.yml'
      - 'extensions/molecule/apache-setup-playbook/**'
      - 'roles/apache/**'
      - 'roles/php/**'
      - 'roles/certificates/**'
  push:
    branches: [ main ]
    paths:
      - 'playbooks/apache-setup.yml'
      - 'extensions/molecule/apache-setup-playbook/**'
      - 'roles/apache/**'
      - 'roles/php/**'
      - 'roles/certificates/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-role-ci:
    uses: ./.github/workflows/role_ci.yml
    with:
      role-name: 'apache_setup_playbook'
