name: CI - apache

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'roles/apache/**'
      - 'extensions/molecule/apache/**'
  push:
    branches: [ main ]
    paths:
      - 'roles/apache/**'
      - 'extensions/molecule/apache/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-test-ci:
    uses: ./.github/workflows/test_ci.yml
    with:
      test-name: 'apache'
      test-type: 'role'
