name: CI - php

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'roles/php/**'
      - 'extensions/molecule/php/**'
  push:
    branches: [ main ]
    paths:
      - 'roles/php/**'
      - 'extensions/molecule/php/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-test-ci:
    uses: ./.github/workflows/test_ci.yml
    with:
      test-name: 'php'
      test-type: 'role'
